### ISSUE TITLE
Pretty hands

### ISSUE THREAD

**Issue by mrcfschr** [Nakamir-Code/SKRecording#1]
current hands https://drive.google.com/file/d/1dPk6ZTBRLkbhc4SRMvfTMvDpAz7fGn_4/view?usp=sharing
Get MRTK Hands working in SK:

**Comment by mrcfschr** [comment]
Unreal mrtk hand looks best https://github.com/microsoft/MixedReality-UXTools-Unreal/tree/public/0.12.x-UE4.27/UXToolsGame/Plugins/UXTools/Content/XRSimulation @austinbhale  uses this one in his demos

**Comment by mrcfschr** [comment]
how not  to import
![image](https://user-images.githubusercontent.com/57159035/166006573-2a65cf03-f5e4-4d30-971c-e952e0faa25a.png)
How to import:
![image](https://user-images.githubusercontent.com/57159035/166006733-9a20613f-fb50-4be6-835b-df57c2fe6fb1.png)
![image](https://user-images.githubusercontent.com/57159035/166006905-c631f371-7c75-4db0-b7d8-80312601d3f3.png)

select armature viewport in front to visualize

**Comment by mrcfschr** [comment]
clean up rig (remove everything except deform bones, e.g. remove ik bones):
![image](https://user-images.githubusercontent.com/57159035/166007367-0d7d17ee-bded-417d-8c98-10027cf6bcb9.png)

**Comment by mrcfschr** [comment]
reset pose position to rest position in pose mode (Pose top left-> clear transforms)

**Comment by mrcfschr** [comment]
make sure rig matches stereokit 
![image](https://user-images.githubusercontent.com/57159035/166013326-63518ebb-b19a-49a5-a0fe-bb0885944ba3.png)
![image](https://user-images.githubusercontent.com/57159035/166015007-4e8aab09-b4e0-4e7e-b26e-d35015b3b955.png)
![image](https://user-images.githubusercontent.com/57159035/166016495-afc06ce1-a82f-4b38-aff5-ba5870ee7256.png)

**Comment by mrcfschr** [comment]
vs: 
![image](https://user-images.githubusercontent.com/57159035/166028406-71a011f1-a930-4e79-bb26-70caf64f996b.png)
The rigs seem to match
except
![image](https://user-images.githubusercontent.com/57159035/166061298-afebc0c1-c6a0-4f1b-a9eb-bbe6fc696e71.png)

**Comment by mrcfschr** [comment]
also tried adding material not the right texs tho - will do later should be easy at the end
![image](https://user-images.githubusercontent.com/57159035/166046649-bea844f6-4716-49cb-baf6-8cd3bcb9f6fe.png)

**Comment by mrcfschr** [comment]
let's try the rig in Stereokit using SK record: (apply location, rotation and scale and export as gltf using standard export settings)
Rename rig joints to stereokit joints before for simplicitiy

**Comment by mrcfschr** [comment]
should be able to automate find node from finger and joint id now:
![image](https://user-images.githubusercontent.com/57159035/166060331-5dea6f13-4fd6-47cb-a77d-964d31d7eafc.png)
 testing right hand (changed joint info from struct to class):
```
 else
            {
                handModel = Model.FromFile("Hand_RIGHT.glb");
                foreach (JointInfo j in jointInfo)
                {
                    string jointName = j.finger.ToString() + "." + j.joint.ToString()+ ".RIGHT";
                    j.node = handModel.FindNode(jointName);
                }
                
            }
```

**Comment by mrcfschr** [comment]
renamed thumb root to knucklemajor- same value but skrecording used other one

**Comment by mrcfschr** [comment]
![image](https://user-images.githubusercontent.com/57159035/166068438-aa695c18-fe1d-42ab-9b94-d425c133a118.png)
90 deg rotation seems wrong/ wrist joint is not animated, seems to just go with several nodes / different from mrtk system

**Comment by mrcfschr** [comment]
I need to transfer these weights or set the wrist bone using a wrist pose which sk doesn't seem to have according to the documentation
![image](https://user-images.githubusercontent.com/57159035/166068812-452f3e9d-1443-40cd-b0b9-5d8d5f64c96d.png)

**Comment by mrcfschr** [comment]
maybe I should just take the average of all roots?

**Comment by mrcfschr** [comment]
or set wrist to palm with an offset?

**Comment by mrcfschr** [comment]
or just delete bone? seems to work 

![20220429_153022_HoloLens](https://user-images.githubusercontent.com/57159035/166076741-90e47932-51c3-4fdc-97f2-81fc4f20d612.jpg)

**Comment by marcfischer123467** [comment]
also I should probably just render the hand on top of mine to see if the overlay is good

**Comment by mrcfschr** [comment]
but still looks weird, I'll try getting the initial rotations, do I really need to rotate by -90?

**Comment by marcfischer123467** [comment]
why are they setting positions of non root bones?

**Comment by mrcfschr** [comment]
I think I'll try a simpler project where I have my rigged model overlaid over my hand and nothing else

**Comment by mrcfschr** [comment]
the handtracking api is open xr

**Comment by mrcfschr** [comment]
there are  unity/unreal examples using mrtk

**Comment by mrcfschr** [comment]
left rig right sk: ![image](https://user-images.githubusercontent.com/57159035/166087531-f3b839c6-a96e-430e-a104-1b73d294e82e.png)
rig: x right , yup, z toward, (sk coordinate system)
sk handtracking: x left, z down, y forward
Quat rot = Quat.FromAngles(90, 0, 180); should align

**Comment by mrcfschr** [comment]
![image](https://user-images.githubusercontent.com/57159035/166088009-52aac815-5987-4182-98f4-35cbc9b7185b.png)
![image](https://user-images.githubusercontent.com/57159035/166088181-450e5081-e6b0-4228-8d96-5f4962bbef31.png)
no initial rotations needed because my model doesn't have any

**Comment by mrcfschr** [comment]
Only setting root bone pose 
https://drive.google.com/file/d/1FkQ2ccdFaHbp2Jv8FHPr3HqLs23feiyH/view?usp=sharing (no scaling)

**Comment by mrcfschr** [comment]
with scaling( setting all positions, could still use radius to scale hand more accurately) 
https://drive.google.com/file/d/1fhpoIfi5xlXjRadZlw8mhyzelUuzGzoK/view?usp=sharing

**Comment by mrcfschr** [comment]
wrist still looks weird tho, I'll try using the average pose of all roots to move the wrist weights:

**Comment by mrcfschr** [comment]
actually nvm the documentation is wrong it does track wrist
![image](https://user-images.githubusercontent.com/57159035/166089557-f3b4abbf-3aa6-4f73-852e-4c0e3b4d499b.png)

you can get it using
`Pose wrist = Input.Hand(Handed.Right).wrist;`

**Comment by mrcfschr** [comment]
Looks really good: https://drive.google.com/file/d/1ga3mvAZTeQ8DCMTbpXCpRNdjcdAcESMu/view?usp=sharing

**Comment by mrcfschr** [comment]
to get the left hand we can simply mirror the root bone 
![image](https://user-images.githubusercontent.com/57159035/166131949-1e17d841-2611-4079-9e03-a3a22baddfa3.png)
![image](https://user-images.githubusercontent.com/57159035/166131953-b955c275-45a8-4d13-a932-2d44a5dcfd32.png)


to create a left hand model: Apply the armature modifier - armature in rest pose doesn't deform anything, so we need also a mesh to match the new rest pose.

Pose > Apply Pose as Rest Pose. This will set current pose as the rest pose. It sets only bones poses - constraints or custom properties in complicated or badly designed rigs might make the rig act weird with bones in different rest state!

Add the armature modifier back. (drag and drop armature , duplicating before doesn't work)

Tracking both hands:
https://drive.google.com/file/d/1N5tBjeWTF6FjkFXXfSmxwF8mQMgJW6Yw/view?usp=sharing

**Comment by mrcfschr** [comment]
[Why is it that after Mirroring a Mesh, it shows up as Transparent in Unity?](https://blender.stackexchange.com/questions/247920/why-is-it-that-after-mirroring-a-mesh-it-shows-up-as-transparent-in-unity)
accidentally flipped normals while mirroring- had to recalculate outside using alt +N shift N

**Comment by mrcfschr** [comment]
I just implemented the feature on https://github.com/Nakamir-Code/SKRecording/tree/experimental_rigging_hands and send the pull request https://github.com/Nakamir-Code/SKRecording/pull/2 and requested @nschapeler as a reviewer.
I documented my process here:
https://github.com/Nakamir-Code/SKRecording/issues/1
A separate project that just visualizes the hand rendering can be found here https://github.com/Nakamir-Code/RiggedHandVisualizer.
Here is a video of the final result: https://drive.google.com/file/d/14rgsO4MDCH46lmBuQpnazEfMAFDvRMur/view?usp=sharing (I added a time.sleep of 0.4 on the server side so we can see the hands move near the recording speed during playback, timestamp interpolation will be used in the future)
